### ISSUE TITLE
Cannot install via HomeBrew

### ISSUE THREAD

**Issue by markjfisher** [jeffkowalski/geeknote#103]
I'm getting the following error trying to install with homebrew:

    $ brew install --HEAD https://raw.githubusercontent.com/jeffkowalski/geeknote/master/geeknote.rb
    ######################################################################## 100.0%
    ==> Cloning https://github.com/jeffkowalski/geeknote.git
    Updating /Users/my.user/Library/Caches/Homebrew/geeknote--git
    ==> Checking out branch master
    Already on 'master'
    Your branch is up to date with 'origin/master'.
    HEAD is now at 95069db Merge branch 'master' of https://github.com/josswright/geeknote into 2.0.15
    ==> Downloading https://files.pythonhosted.org/packages/33/bc/fa0b5347139cd9564f0d44ebd2b147ac97c36b2403943dbee8a25fd74012/virtualenv-16.0.0.tar.gz
    Already downloaded: /Users/my.user/Library/Caches/Homebrew/downloads/02e9f856894cc3f1979f2bf31e2f709c30ef64ea80ce14a80cc83e384528d06f--virtualenv-16.0.0.tar.gz
    ==> python3 -c import setuptools... --no-user-cfg install --prefix=/private/tmp/geeknote--homebrew-virtualenv-20180918-7934-x1eypl/target --single-version-externally-managed --re
    ==> python3 -s /private/tmp/geeknote--homebrew-virtualenv-20180918-7934-x1eypl/target/bin/virtualenv -p python3 /usr/local/Cellar/geeknote/HEAD-95069db/libexec
    ==> Downloading https://files.pythonhosted.org/packages/a7/2b/0039154583cb0489c8e18313aa91ccd140ada103289c5c5d31d80fd6d186/websocket_client-0.40.0.tar.gz
    Already downloaded: /Users/my.user/Library/Caches/Homebrew/downloads/154a463a6dc825151485c7894fba0717b78d48394aef9c2cc6bbfae9fc20f33c--websocket_client-0.40.0.tar.gz
    ==> /usr/local/Cellar/geeknote/HEAD-95069db/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/geeknote--websocket-client-20180918-7934-hflt79
    ==> Downloading https://files.pythonhosted.org/packages/4e/13/774faf38b445d0b3a844b65747175b2e0500164b7c28d78e34987a5bfe06/ipaddress-1.0.18.tar.gz
    Already downloaded: /Users/my.user/Library/Caches/Homebrew/downloads/6fa30475f4c9fa29ac21c10b794cb9c03a56479bce055fab1949e17e53c241b5--ipaddress-1.0.18.tar.gz
    ==> /usr/local/Cellar/geeknote/HEAD-95069db/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/geeknote--ipaddress-20180918-7934-1dih37n/ipadd
    ==> Downloading https://files.pythonhosted.org/packages/10/a5/a9596229782ffcb465f288588dff39ccd7f64fc453d64f75f5ef442315a8/orderedmultidict-0.7.11.tar.gz
    Already downloaded: /Users/my.user/Library/Caches/Homebrew/downloads/cd5cda7e388ac9284d2d15f2cbc391d473c1ddb65f7d9cffa1dc6b947d0e8630--orderedmultidict-0.7.11.tar.gz
    ==> /usr/local/Cellar/geeknote/HEAD-95069db/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/geeknote--orderedmultidict-20180918-7934-zfvrnc
    ==> Downloading https://files.pythonhosted.org/packages/64/19/8b9066e94088e8d06d649e10319349bfca961e87768a525aba4a2627c986/oauth2-1.9.0.post1.tar.gz
    Already downloaded: /Users/my.user/Library/Caches/Homebrew/downloads/a4332264cdf4a2cf1c9524aafd5a77ce43e807b9b47d98c35387a2c7754897dd--oauth2-1.9.0.post1.tar.gz
    ==> /usr/local/Cellar/geeknote/HEAD-95069db/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/geeknote--oauth2-20180918-7934-1s0z4z8/oauth2-1
    ==> Downloading https://files.pythonhosted.org/packages/e4/2e/a7e27d2c36076efeb8c0e519758968b20389adf57a9ce3af139891af2696/httplib2-0.10.3.tar.gz
    Already downloaded: /Users/my.user/Library/Caches/Homebrew/downloads/af029c925736939ee512d9354f8b6d732a33a1a10c94c29b0429a6a20a546be5--httplib2-0.10.3.tar.gz
    ==> /usr/local/Cellar/geeknote/HEAD-95069db/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/geeknote--httplib2-20180918-7934-1mmhk7s/httpli
    ==> Downloading https://files.pythonhosted.org/packages/3b/8e/dba34913e7dbccd868cdf228c5104f97ad97d4618994f0c5dd456496ae81/evernote-1.25.2.tar.gz
    Already downloaded: /Users/my.user/Library/Caches/Homebrew/downloads/bc717ce6e353af1ef66e9e373941b8d44ce0a8cf0b8258d516bd1abb8d48be9a--evernote-1.25.2.tar.gz
    ==> /usr/local/Cellar/geeknote/HEAD-95069db/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/geeknote--evernote-20180918-7934-8m3bo/evernote
    Last 15 lines from /Users/my.user/Library/Logs/Homebrew/geeknote/08.pip:
      File "/usr/local/Cellar/geeknote/HEAD-95069db/libexec/lib/python3.7/site-packages/pip/_internal/resolve.py", line 102, in resolve
        self._resolve_one(requirement_set, req)
      File "/usr/local/Cellar/geeknote/HEAD-95069db/libexec/lib/python3.7/site-packages/pip/_internal/resolve.py", line 256, in _resolve_one
        abstract_dist = self._get_abstract_dist_for(req_to_install)
      File "/usr/local/Cellar/geeknote/HEAD-95069db/libexec/lib/python3.7/site-packages/pip/_internal/resolve.py", line 209, in _get_abstract_dist_for
        self.require_hashes
      File "/usr/local/Cellar/geeknote/HEAD-95069db/libexec/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 298, in prepare_linked_requirement
        abstract_dist.prep_for_dist(finder, self.build_isolation)
      File "/usr/local/Cellar/geeknote/HEAD-95069db/libexec/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 126, in prep_for_dist
        self.req.run_egg_info()
      File "/usr/local/Cellar/geeknote/HEAD-95069db/libexec/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 636, in run_egg_info
        command_desc='python setup.py egg_info')
      File "/usr/local/Cellar/geeknote/HEAD-95069db/libexec/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 701, in call_subprocess
        % (command_desc, proc.returncode, cwd))
    pip._internal.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-req-build-i0uucln9/
    /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:49:in `write': Broken pipe (Errno::EPIPE)
	    from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:49:in `puts'
	    from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:49:in `rescue in block (3 levels) in safe_fork'
	    from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:31:in `block (3 levels) in safe_fork'
	    from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:30:in `fork'
	    from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:30:in `block (2 levels) in safe_fork'
	    from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:27:in `open'
	    from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:27:in `block in safe_fork'
	    from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
	    from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:26:in `safe_fork'
	    from /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:729:in `build'
	    from /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:317:in `install'
	    from /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:325:in `install_formula'
	    from /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:256:in `block in install'
	    from /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:254:in `each'
	    from /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:254:in `install'
	    from /usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
    
    Do not report this issue to Homebrew/brew or Homebrew/core!

Are there any prerequisites I'm missing? Searching for the particular error lead to suggestions of globally installing setuptools, but if I'm reading the history above correctly, it's doing that at the start (my python isn't my strongest language), and generally isn't a good idea anyway.

**Comment by markjfisher** [comment]
Thanks
