### ISSUE TITLE
gnsync: UnicodeDecodeError: 'ascii' codec can't decode byte

### ISSUE THREAD

**Issue by WhyNotHugo** [jeffkowalski/geeknote#109]
Trying to just download my existing notes via `gnsync`, I noticed a lot of my notes weren't getting downloaded, but were being silently skipped.

There's no warning or indication of failure:
```
# gnsync --path /backups --format markdown --notebook Default --download-only
#
```

But error.log shows more details:
```
2018-12-01 03:41:13,401 gnsync __init__ 146 : Sync Start
2018-12-01 03:41:15,082 gnsync wrapper 55 : 'ascii' codec can't decode byte 0xc3 in position 808: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/geeknote/gnsync.py", line 53, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/geeknote/gnsync.py", line 383, in _create_file
    content = Editor.ENMLtoText(note.content.encode('utf-8'), self.imageOptions)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 808: ordinal not in range(128)
2018-12-01 03:41:16,273 gnsync wrapper 55 : 'ascii' codec can't decode byte 0xc3 in position 414: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/geeknote/gnsync.py", line 53, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/geeknote/gnsync.py", line 383, in _create_file
    content = Editor.ENMLtoText(note.content.encode('utf-8'), self.imageOptions)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 414: ordinal not in range(128)
2018-12-01 03:41:16,899 gnsync wrapper 55 : 'ascii' codec can't decode byte 0xc3 in position 134: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/geeknote/gnsync.py", line 53, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/geeknote/gnsync.py", line 383, in _create_file
    content = Editor.ENMLtoText(note.content.encode('utf-8'), self.imageOptions)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 134: ordinal not in range(128)
2018-12-01 03:41:17,488 gnsync wrapper 55 : 'ascii' codec can't decode byte 0xc3 in position 226: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/geeknote/gnsync.py", line 53, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/geeknote/gnsync.py", line 383, in _create_file
    content = Editor.ENMLtoText(note.content.encode('utf-8'), self.imageOptions)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 226: ordinal not in range(128)
2018-12-01 03:41:18,068 gnsync wrapper 55 : 'ascii' codec can't decode byte 0xc3 in position 915: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/geeknote/gnsync.py", line 53, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/geeknote/gnsync.py", line 383, in _create_file
    content = Editor.ENMLtoText(note.content.encode('utf-8'), self.imageOptions)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 915: ordinal not in range(128)
2018-12-01 03:41:18,874 gnsync wrapper 55 : 'ascii' codec can't decode byte 0xc2 in position 377: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/geeknote/gnsync.py", line 53, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/geeknote/gnsync.py", line 383, in _create_file
    content = Editor.ENMLtoText(note.content.encode('utf-8'), self.imageOptions)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 377: ordinal not in range(128)
2018-12-01 03:41:19,691 gnsync wrapper 55 : 'ascii' codec can't decode byte 0xc3 in position 464: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/geeknote/gnsync.py", line 53, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/geeknote/gnsync.py", line 383, in _create_file
    content = Editor.ENMLtoText(note.content.encode('utf-8'), self.imageOptions)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 464: ordinal not in range(128)
2018-12-01 03:41:20,865 gnsync wrapper 55 : 'ascii' codec can't decode byte 0xc3 in position 188: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/geeknote/gnsync.py", line 53, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/geeknote/gnsync.py", line 383, in _create_file
    content = Editor.ENMLtoText(note.content.encode('utf-8'), self.imageOptions)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 188: ordinal not in range(128)
2018-12-01 03:41:21,455 gnsync wrapper 55 : 'ascii' codec can't decode byte 0xc3 in position 167: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/geeknote/gnsync.py", line 53, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/geeknote/gnsync.py", line 383, in _create_file
    content = Editor.ENMLtoText(note.content.encode('utf-8'), self.imageOptions)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 167: ordinal not in range(128)
2018-12-01 03:41:22,051 gnsync wrapper 55 : 'ascii' codec can't decode byte 0xc2 in position 443: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/geeknote/gnsync.py", line 53, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/geeknote/gnsync.py", line 383, in _create_file
    content = Editor.ENMLtoText(note.content.encode('utf-8'), self.imageOptions)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 443: ordinal not in range(128)
2018-12-01 03:41:22,926 gnsync wrapper 55 : 'ascii' codec can't decode byte 0xc3 in position 165: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/geeknote/gnsync.py", line 53, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/geeknote/gnsync.py", line 383, in _create_file
    content = Editor.ENMLtoText(note.content.encode('utf-8'), self.imageOptions)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 165: ordinal not in range(128)
2018-12-01 03:41:24,729 gnsync wrapper 55 : 'ascii' codec can't decode byte 0xc3 in position 140: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/geeknote/gnsync.py", line 53, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/geeknote/gnsync.py", line 383, in _create_file
    content = Editor.ENMLtoText(note.content.encode('utf-8'), self.imageOptions)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 140: ordinal not in range(128)
2018-12-01 03:41:25,305 gnsync wrapper 55 : 'ascii' codec can't decode byte 0xc3 in position 148: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/geeknote/gnsync.py", line 53, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/geeknote/gnsync.py", line 383, in _create_file
    content = Editor.ENMLtoText(note.content.encode('utf-8'), self.imageOptions)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 148: ordinal not in range(128)
2018-12-01 03:41:25,891 gnsync wrapper 55 : 'ascii' codec can't decode byte 0xc2 in position 190: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/geeknote/gnsync.py", line 53, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/geeknote/gnsync.py", line 383, in _create_file
    content = Editor.ENMLtoText(note.content.encode('utf-8'), self.imageOptions)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 190: ordinal not in range(128)
2018-12-01 03:41:26,489 gnsync wrapper 55 : 'ascii' codec can't decode byte 0xc3 in position 151: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/geeknote/gnsync.py", line 53, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/geeknote/gnsync.py", line 383, in _create_file
    content = Editor.ENMLtoText(note.content.encode('utf-8'), self.imageOptions)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 151: ordinal not in range(128)
2018-12-01 03:41:27,679 gnsync wrapper 55 : 'ascii' codec can't decode byte 0xc2 in position 218: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/geeknote/gnsync.py", line 53, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/geeknote/gnsync.py", line 383, in _create_file
    content = Editor.ENMLtoText(note.content.encode('utf-8'), self.imageOptions)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 218: ordinal not in range(128)
2018-12-01 03:41:30,056 gnsync wrapper 55 : 'ascii' codec can't decode byte 0xc3 in position 2207: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/geeknote/gnsync.py", line 53, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/geeknote/gnsync.py", line 383, in _create_file
    content = Editor.ENMLtoText(note.content.encode('utf-8'), self.imageOptions)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2207: ordinal not in range(128)
2018-12-01 03:41:33,674 gnsync wrapper 55 : 'ascii' codec can't decode byte 0xc3 in position 206: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/geeknote/gnsync.py", line 53, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/geeknote/gnsync.py", line 383, in _create_file
    content = Editor.ENMLtoText(note.content.encode('utf-8'), self.imageOptions)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 206: ordinal not in range(128)
2018-12-01 03:41:35,406 gnsync wrapper 55 : 'ascii' codec can't decode byte 0xc3 in position 168: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/geeknote/gnsync.py", line 53, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/geeknote/gnsync.py", line 383, in _create_file
    content = Editor.ENMLtoText(note.content.encode('utf-8'), self.imageOptions)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 168: ordinal not in range(128)
2018-12-01 03:41:36,573 gnsync wrapper 55 : 'ascii' codec can't decode byte 0xc3 in position 192: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/geeknote/gnsync.py", line 53, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/geeknote/gnsync.py", line 383, in _create_file
    content = Editor.ENMLtoText(note.content.encode('utf-8'), self.imageOptions)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 192: ordinal not in range(128)
2018-12-01 03:41:37,153 gnsync sync 224 : Sync Complete
```

**Comment by ryanerwin** [comment]
I'm getting the same UnicodeDecodeError 'ascii' codec error when trying to backup my evernote database via `gnsync`... Specifically, so far I'm getting failure to convert on the following UTF-8 sequences:

* `u'\xa0'` (no break space)
* `u'\u2019'`  (right single quotation mark)
* `u'\u2026'`(HORIZONTAL ELLIPSIS)
* `u'\u2014'` (EM DASH)
* `u'\U0001f4b0'`(MONEY BAG)

Here's a excerpt from the log...

I found a StackExchange post that may help...

https://stackoverflow.com/questions/9942594/unicodeencodeerror-ascii-codec-cant-encode-character-u-xa0-in-position-20

```
1440 2019-05-15 09:32:06,174 : 'ascii' codec can't encode character u'\xa0' in position 1531: ordinal not in range(128)
1441 Traceback (most recent call last):
1442   File "/usr/lib/python2.7/site-packages/geeknote/gnsync.py", line 53, in wrapper
1443     return func(*args, **kwargs)
1444   File "/usr/lib/python2.7/site-packages/geeknote/gnsync.py", line 368, in _create_file
1445     imageList = Editor.getImages(note.content)
1446   File "/usr/lib/python2.7/site-packages/geeknote/editor.py", line 60, in getImages
1447     soup = BeautifulSoup(contentENML.decode('utf-8'))
1448   File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
1449     return codecs.utf_8_decode(input, errors, True)
1450 UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 1531: ordinal not in range(128)
1451 2019-05-15 09:32:18,769 : 'ascii' codec can't encode character u'\U0001f4b0' in position 308: ordinal not in range(
1452 Traceback (most recent call last):
1453   File "/usr/lib/python2.7/site-packages/geeknote/gnsync.py", line 53, in wrapper
1454     return func(*args, **kwargs)
1455   File "/usr/lib/python2.7/site-packages/geeknote/gnsync.py", line 368, in _create_file
1456     imageList = Editor.getImages(note.content)
1457   File "/usr/lib/python2.7/site-packages/geeknote/editor.py", line 60, in getImages
1458     soup = BeautifulSoup(contentENML.decode('utf-8'))
1459   File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
1460     return codecs.utf_8_decode(input, errors, True)
1461 UnicodeEncodeError: 'ascii' codec can't encode character u'\U0001f4b0' in position 308: ordinal not in range(128)
```
