### ISSUE TITLE
Cannot login with correct token

### ISSUE THREAD

**Issue by Mladia** [jeffkowalski/geeknote#112]
I am trying to login with the correct token, but it doesn't really seem to work.

I tried with `export EVERNOTE_DEV_TOKEN=...` and also supplying it directly on
`➜ geeknote login
OAuth token request failed              
If you have an Evernote developer token, enter it here:..`

I also tried different terminal emulators. I read that this errorCode means that the authentication is not successful, which is simply not right.
` ➜ geeknote login                                 
>> : Connecting to Evernote...Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/geeknote/geeknote.py", line 1416, in main
    User().login(**ARGS)
  File "/usr/lib/python2.7/site-packages/geeknote/geeknote.py", line 40, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/geeknote/geeknote.py", line 606, in login
    if self.getEvernote().auth():
  File "/usr/lib/python2.7/site-packages/geeknote/geeknote.py", line 225, in auth
    userInfo = self.getUserInfo()
  File "/usr/lib/python2.7/site-packages/geeknote/geeknote.py", line 234, in getUserInfo
    return self.getUserStore().getUser(self.authToken)
  File "/usr/lib/python2.7/site-packages/evernote/edam/userstore/UserStore.py", line 1001, in getUser
    return self.recv_getUser()
  File "/usr/lib/python2.7/site-packages/evernote/edam/userstore/UserStore.py", line 1027, in recv_getUser
    raise result.systemException
EDAMSystemException: EDAMSystemException(errorCode=8, rateLimitDuration=None, _message=u'authenticationToken')`

**Comment by jeffkowalski** [comment]
Interestingly, using geeknote 2.0.17, I am seeing a similar condition. I'll have to wait a few more days to debug it though.  (My onsite backups crashed, and I need to wait for offsite to be restored.)

>>> : Connecting to Evernote...Traceback (most recent call last):
  File "/home/jeff/.local/lib/python2.7/site-packages/geeknote/geeknote.py", line 1441, in main
    Notes().show(**ARGS)
  File "/home/jeff/.local/lib/python2.7/site-packages/geeknote/geeknote.py", line 1066, in show
    self.connectToEvernote()
  File "/home/jeff/.local/lib/python2.7/site-packages/geeknote/geeknote.py", line 543, in connectToEvernote
    self.evernote = GeekNote()
  File "/home/jeff/.local/lib/python2.7/site-packages/geeknote/geeknote.py", line 100, in __init__
    self.auth()
  File "/home/jeff/.local/lib/python2.7/site-packages/geeknote/geeknote.py", line 225, in auth
    userInfo = self.getUserInfo()
  File "/home/jeff/.local/lib/python2.7/site-packages/geeknote/geeknote.py", line 234, in getUserInfo
    return self.getUserStore().getUser(self.authToken)
  File "/home/jeff/.local/lib/python2.7/site-packages/evernote/edam/userstore/UserStore.py", line 1033, in getUser
    return self.recv_getUser()
  File "/home/jeff/.local/lib/python2.7/site-packages/evernote/edam/userstore/UserStore.py", line 1056, in recv_getUser
    raise result.userException
EDAMUserException: EDAMUserException(errorCode=9, parameter='authenticationToken')

**Comment by jeffkowalski** [comment]
In my case, it was an expired developer token.
I retrieved a new one at https://www.evernote.com/api/DeveloperToken.action

When using a dev token, I don't believe it's necessary to login.
You should be able to simply invoke a command and the credentials will automatically be applied and stored.

Try removing the database.db file in ~/.geeknote, to get rid of any obsolete credentials, then issue a command with the new token, like

```
env EVERNOTE_DEV_TOKEN="<your token>"  geeknote find --tag "-*"
```

**Comment by Mladia** [comment]
I tried it once again today and it really did work.
