### ISSUE TITLE
Exception on --version after install

### ISSUE THREAD

**Issue by vitaly-zdanevich** [jeffkowalski/geeknote#118]
```
Traceback (most recent call last):
  File "/usr/local/bin/geeknote", line 9, in <module>
    load_entry_point('geeknote==2.0.9', 'console_scripts', 'geeknote')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/geeknote/geeknote.py", line 29, in <module>
    from oauth import GeekNoteAuth
  File "/usr/local/lib/python2.7/dist-packages/geeknote/oauth.py", line 11, in <module>
    from lxml import html
  File "/usr/local/lib/python2.7/dist-packages/lxml/html/__init__.py", line 54, in <module>
    from .. import etree
ImportError: /usr/local/lib/python2.7/dist-packages/lxml/etree.so: undefined symbol: PyFPE_jbuf
```

Xubuntu 18.04.3 i686

**Comment by jeffkowalski** [comment]
The stack backtrace alone is not enough for me to debug this.  
What OS are you using?  
How did you install geeknote (via what command)?
Also "--version" is not a command or switch.  What were you trying to accomplish? To get the version of geeknote, just issue "geeknote".
The current release is 2.0.18.  It looks like you were trying to use 2.0.9.  I'd recommend an update.

**Comment by vitaly-zdanevich** [comment]
Hm, yes, 2.0.9, strange, looks like previous version was not removed properly...

I cloned this repository and did:
```
python2 setup.py build
pip2 install --upgrade .
```
But `geeknote` executable was not added to PATH.
