### ISSUE TITLE
after installing from brew: pkg_resources.DistributionNotFound: The 'docker-py>=1.8' distribution was not found and is required by proxyenv

### ISSUE THREAD

**Issue by vitaly-zdanevich** [jeffkowalski/geeknote#41]
Traceback (most recent call last):
  File "/usr/local/Cellar/geeknote/HEAD/libexec/bin/geeknote", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 635, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'docker-py>=1.8' distribution was not found and is required by proxyenv

**Comment by emKaroly** [comment]
Install pip and proxyenv:

On OSX i did this:
sudo easy_install pip
pip install proxyenv

**Comment by jeffkowalski** [comment]
Fixed in v2.0.1 de252b7db2293ea4cf53dd93769e93866445d16c

**Comment by romariolopezc** [comment]
I just installed this and I had the same error. I have to install pip2 and `$ pip install proxyenv`.

Arch Linux package from the AUR
