### ISSUE TITLE
Cannot edit note - AttributeError: 'Note' object has no attribute 'url'

### ISSUE THREAD

**Issue by brhahlen** [jeffkowalski/geeknote#57]
I am getting the following error when trying to edit a previously created note (via geeknote):
```
$ geeknote edit --note "2"
 >> : Connecting to Evernote...Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/geeknote/geeknote.py", line 1220, in main
    Notes().edit(**ARGS)
  File "/usr/lib/python2.7/site-packages/geeknote/geeknote.py", line 835, in edit
    inputData = self._parseInput(title, content, tag, created, notebook, resource, note, reminder, url)
  File "/usr/lib/python2.7/site-packages/geeknote/geeknote.py", line 954, in _parseInput
    result['url'] = note.url
AttributeError: 'Note' object has no attribute 'url'
```
How to fix this?

**Comment by jeffkowalski** [comment]
Thank you.  It should be fixed now via the commit above.

**Comment by brhahlen** [comment]
Switched to branch 2.0.7 and works now.
Thanks for the quick fix!
