### ISSUE TITLE
geeknote create --title 'gcalclirc' --tag gcalcli --resource ~/.gcalclirc

### ISSUE THREAD

**Issue by vitaly-zdanevich** [jeffkowalski/geeknote#67]
```
>>  : Connecting to Evernote...Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/geeknote/geeknote.py", line 1229, in main
    Notes().create(**ARGS)
  File "/usr/local/lib/python2.7/dist-packages/geeknote/geeknote.py", line 815, in create
    self.connectToEvernote()
  File "/usr/local/lib/python2.7/dist-packages/geeknote/geeknote.py", line 485, in connectToEvernote
    self.evernote = GeekNote()
  File "/usr/local/lib/python2.7/dist-packages/geeknote/geeknote.py", line 94, in __init__
    self.getUserStore()
  File "/usr/local/lib/python2.7/dist-packages/geeknote/geeknote.py", line 155, in getUserStore
    self.checkVersion()
  File "/usr/local/lib/python2.7/dist-packages/geeknote/geeknote.py", line 173, in checkVersion
    UserStoreConstants.EDAM_VERSION_MINOR)
  File "/usr/local/lib/python2.7/dist-packages/evernote/edam/userstore/UserStore.py", line 490, in checkVersion
    self.send_checkVersion(clientName, edamVersionMajor, edamVersionMinor)
  File "/usr/local/lib/python2.7/dist-packages/evernote/edam/userstore/UserStore.py", line 501, in send_checkVersion
    self._oprot.trans.flush()
  File "/usr/local/lib/python2.7/dist-packages/thrift/transport/THttpClient.py", line 125, in _f
    result = f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/thrift/transport/THttpClient.py", line 151, in flush
    self.__http.endheaders()
  File "/usr/lib/python2.7/httplib.py", line 1013, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 864, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 826, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1216, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 553, in create_connection
>>> : Connecting to Evernote...    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno -2] Name or service not known

```
version: 2.0.9

**Comment by jeffkowalski** [comment]
This indicates that your connection to the internet was momentarily down when the command was run.  If I'm incorrect, please provide steps to reproduce the problem.
