### ISSUE TITLE
after `brew reinstall geeknote`: missing dependency

### ISSUE THREAD

**Issue by vitaly-zdanevich** [jeffkowalski/geeknote#69]
```
$ geeknote
Traceback (most recent call last):
  File "/usr/local/Cellar/geeknote/HEAD-2b5f8fc/libexec/bin/geeknote", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 635, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'lxml' distribution was not found and is required by geeknote
```

after `pip2 install lxml` it is fixed.

**Comment by jeffkowalski** [comment]
```geeknote.rb``` expresses a dependency on ```lxml``` 
Maybe that's not enough.
What would you propose as a fix?

**Comment by arumoy-shome** [comment]
I did a `pip2 install lxml` as suggested above but I still get the same error? Are there any updates on this issue?

**Comment by jeffkowalski** [comment]
@arumoy-shome, does ```sudo apt-get install python-lxml``` resolve the error?
