### ISSUE TITLE
gnsync: gaierror: [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by SilkAndSlug** [jeffkowalski/geeknote#71]
Hi Jeff,

Thanks for fixing [Issue #60](https://github.com/jeffkowalski/geeknote/issues/70). All notes download from one notebook, and 114 (of 1403) from the second. Gnsync then exits with the below:

    user@host:~/.backups/evernote$ gnsync --download-only --all
    Operation failed
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/geeknote/geeknote.py", line 106, in wrapper
        result = func(wrapped_object, *args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/geeknote/geeknote.py", line 270, in loadNoteContent
        tag = self.getNoteStore().getTag(self.authToken, guid)
      File "build/bdist.linux-x86_64/egg/evernote/edam/notestore/NoteStore.py", line 3231, in getTag
        self.send_getTag(authenticationToken, guid)
      File "build/bdist.linux-x86_64/egg/evernote/edam/notestore/NoteStore.py", line 3241, in send_getTag
        self._oprot.trans.flush()
      File "build/bdist.linux-x86_64/egg/thrift/transport/THttpClient.py", line 107, in _f
        result = f(*args, **kwargs)
      File "build/bdist.linux-x86_64/egg/thrift/transport/THttpClient.py", line 141, in flush
        self.__http.endheaders()
      File "/usr/lib/python2.7/httplib.py", line 1035, in endheaders
        self._send_output(message_body)
      File "/usr/lib/python2.7/httplib.py", line 879, in _send_output
        self.send(msg)
      File "/usr/lib/python2.7/httplib.py", line 841, in send
        self.connect()
      File "/usr/lib/python2.7/httplib.py", line 1242, in connect
        HTTPConnection.connect(self)
      File "/usr/lib/python2.7/httplib.py", line 822, in connect
        self.timeout, self.source_address)
      File "/usr/lib/python2.7/socket.py", line 553, in create_connection
        for res in getaddrinfo(host, port, 0, SOCK_STREAM):
    gaierror: [Errno -2] Name or service not known

I'm using v2.0.10, as per Issue #60.

Yours,
Steve

**Comment by jeffkowalski** [comment]
The error means that you were not reliably connected to the internet at the time.  Perhaps you were using a laptop and moved from your wifi signal?
