### ISSUE TITLE
Missing parenthese in call to exec x

### ISSUE THREAD

**Issue by madchap** [jeffkowalski/geeknote#73]
Hi,

Following the README, it seems it doesn't want to install.
I am on Opensuse Tumbleweed.

```
$ python --version
Python 2.7.13
```

```
$ sudo pip install --upgrade .
Processing /home/fblaise/gitrepos/jeffkowalski_geeknote
Collecting evernote>=1.25 (from geeknote==2.0.9)
  Using cached evernote-1.25.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ny4r58uh/evernote/setup.py", line 6
        exec x
             ^
    SyntaxError: Missing parentheses in call to 'exec'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ny4r58uh/evernote/
```

Thanks for your help.
Cheers,
fred

**Comment by madchap** [comment]
Close this... "pip" was linked to python3, used pip2 instead, works fine then. Thanks.
